sudo: false
language: go
go: 1.4.2
before_install:
- export PATH=$HOME/gopath/bin:$PATH
- go get github.com/tools/godep
script:
- godep go test ./...
- make deb-local
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then pip install --user awscli && ~/.local/bin/aws s3 cp --acl public-read deb/*.deb s3://heroku-hsup; fi
notifications:
  email: false
cache:
  directories:
  - $HOME/.local
