sudo: false
language: go
go: 1.4.2
before_install:
- export PATH=$HOME/gopath/bin:$PATH
- go get github.com/tools/godep
script:
- godep go test ./...
- make deb-local
- pip install --user awscli
- ~/.local/bin/aws s3 cp --acl public-read deb/*.deb s3://heroku-hsup
notifications:
  email: false
cache:
  directories:
  - $HOME/.local
